import React, { useState } from 'react';
import {
  FileText,
  Printer,
  Copy,
  Check,
  X,
  ShieldCheck,
  Download,
  Share2,
} from 'lucide-react';

interface ClinicalSummaryModalProps {
  summaryText: string;
  onClose: () => void;
}

export const ClinicalSummaryModal: React.FC<ClinicalSummaryModalProps> = ({
  summaryText,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(summaryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    const blob = new Blob([summaryText], { type: 'text/plain;charset=utf-8' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `OnlineMedicare-Clinical-Summary-${Date.now()}.txt`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs">
      <div className="bg-white rounded-3xl max-w-2xl w-full p-6 sm:p-8 shadow-2xl border border-teal-200 max-h-[90vh] flex flex-col animate-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="flex items-start justify-between pb-4 border-b border-slate-100 no-print">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-teal-50 text-teal-700 flex items-center justify-center font-bold">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-lg text-slate-900 font-heading">
                Clinical Telehealth Summary & Care Plan
              </h3>
              <p className="text-xs text-slate-400">
                Official encounter record generated by Online mediCare Clinical AI
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="p-2 text-slate-500 hover:text-teal-700 hover:bg-slate-50 rounded-xl transition cursor-pointer"
              title="Copy to clipboard"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            </button>
            <button
              onClick={handlePrint}
              className="p-2 text-slate-500 hover:text-teal-700 hover:bg-slate-50 rounded-xl transition cursor-pointer"
              title="Print document"
            >
              <Printer className="w-4 h-4" />
            </button>
            <button
              onClick={handleDownload}
              className="p-2 text-slate-500 hover:text-teal-700 hover:bg-slate-50 rounded-xl transition cursor-pointer"
              title="Download text file"
            >
              <Download className="w-4 h-4" />
            </button>
            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-slate-600 rounded-xl transition cursor-pointer ml-1"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Document Body */}
        <div className="flex-1 overflow-y-auto py-5 pr-2 space-y-4 text-slate-800 text-xs sm:text-sm font-sans leading-relaxed">
          {/* Letterhead */}
          <div className="p-4 bg-slate-50 border border-slate-200 rounded-2xl flex items-center justify-between">
            <div>
              <span className="font-extrabold text-slate-900 text-base font-heading">
                Online <span className="text-teal-600">mediCare</span>
              </span>
              <p className="text-[11px] text-slate-500">
                Telehealth Consultations & Verified Medical AI Triage
              </p>
            </div>
            <div className="text-right text-[11px] text-slate-500">
              <span className="font-bold text-slate-700 block">Encounter Date:</span>
              <span>{new Date().toLocaleDateString()}</span>
            </div>
          </div>

          {/* Formatted Markdown Content */}
          <div className="p-5 bg-white border border-slate-200 rounded-2xl whitespace-pre-wrap font-sans text-xs sm:text-sm text-slate-800 space-y-3 shadow-inner">
            {summaryText}
          </div>

          {/* Legal / Medical Disclaimer Box */}
          <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl text-[11px] text-amber-900 flex items-start gap-2">
            <ShieldCheck className="w-4 h-4 text-amber-700 shrink-0 mt-0.5" />
            <span>
              <strong>Medical Disclaimer:</strong> This clinical encounter summary is compiled from the patient's reported symptoms and validated against public medical authorities (WHO, CDC, MedlinePlus). It serves as an informative triage record to facilitate communication with your licensed physician.
            </span>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="pt-4 border-t border-slate-100 flex items-center justify-end gap-2 no-print">
          <button
            onClick={onClose}
            className="px-5 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs sm:text-sm rounded-xl transition cursor-pointer"
          >
            Close
          </button>
          <button
            onClick={handlePrint}
            className="px-5 py-2.5 bg-teal-600 hover:bg-teal-700 text-white font-bold text-xs sm:text-sm rounded-xl transition shadow-md flex items-center gap-1.5 cursor-pointer"
          >
            <Printer className="w-4 h-4" />
            Print or Save as PDF
          </button>
        </div>
      </div>
    </div>
  );
};
